# -*- coding: utf-8 -*-
{
    'name': 'Company ERP customization',
    'version': '1.16.0',
    'author': 'Maach Services',
    'description': """This module is used to auto configure odoo modules, setups and modules required for companies""",
    'summary': 'ERP Configuration application for Companies',
    'category': 'Base',
    'depends': [
        'base', 
        'account',
        'ik_multi_branch', 
        'account_accountant', 
        'purchase', 
        'stock', 
        'sale_management',
        'sale_stock',
        'purchase_stock',
        'hr_expense',
        'hr_holidays',
        'hr_attendance',
        'hr_payroll',
        'mail', 
        'hr', 
        'contacts', 
        'hr_holidays', 
        'hr_recruitment', 
        'documents',
        'auditlog',
        'auth_session_timeout',
        'eedc_addons',
        'hr_pms',
        'maach_payment_schedule',
        'migration_app',
        'portal_request',
        'industry_fsm',
        'account_asset',
        'website_crm',
        'website_sale_dashboard',
        'website_helpdesk',
        'hr_payroll_attendance',
        'pos_epson_printer',
        'pos_discount',
        'crm_livechat',
        'attachment_indexation',
        'account_reports',
        'account_fleet',
        'account_followup',
        'account_debit_note',
        'account_check_printing',
        'account_budget',
        'account_batch_payment',
        'hr_contract_salary_payroll',
        'hr_payroll_account',
        'board',
        'website_sale_digital',
        'website_payment',
        'sale_crm',

        ],
    'data': [
        'security/security_group.xml', 
        # 'security/ir.model.access.csv',
        'data/base_config.xml',
    ],
    'assets': {'web.assets_backend': [
        # '/company_memo/static/src/js/hide_function.js',
    ]},
    # 'qweb': [
    #     'static/src/xml/base.xml',
    # ],
    'price': 1305.00,
    'sequence': 1,
    'currency': 'EUR',
    'installable': True,
    'auto_install': False,
}
